twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        mailer_from_address: '%mailer_from_address%'

when@test:
    twig:
        strict_variables: true
